services:
  shell:
    build:
      context: ../..
      dockerfile: docker/shell/Dockerfile
    container_name: ordeck-shell
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - ordeck-net

networks:
  ordeck-net:
    external: true
