services:
  lazuros-widget:
    build:
      context: ../../
      dockerfile: docker/lazuros/Dockerfile.widget
    container_name: ordeck-lazuros-widget
    restart: unless-stopped
    ports:
      - "3002:80"
    networks:
      - ordeck-net

networks:
  ordeck-net:
    external: true
