services:
  lazuros-plugin:
    build:
      context: ../../
      dockerfile: docker/lazuros/Dockerfile.plugin
    container_name: ordeck-lazuros-plugin
    restart: unless-stopped
    ports:
      - "3002:80"
    networks:
      - ordeck-net

networks:
  ordeck-net:
    external: true
